INSERT INTO USER (USER_ID, USERNAME, PASSWORD, ACTIVATED) VALUES ('admin@jincrates.me', 'admin', 'admin', 1);
INSERT INTO USER (USER_ID, USERNAME, PASSWORD, ACTIVATED) VALUES ('user@jincrates.me', 'user', 'user', 1);

INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_USER');
INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values ('admin@jincrates.me', 'ROLE_USER');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values ('admin@jincrates.me', 'ROLE_ADMIN');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values ('user@jincrates.me', 'ROLE_USER');
