INSERT INTO USER (ID, EMAIL, USERNAME, PASSWORD, ACTIVATED) VALUES (1, 'admin@jincrates.me', 'admin', 'admin', 1);
INSERT INTO USER (ID, EMAIL, USERNAME, PASSWORD, ACTIVATED) VALUES (2, 'user@jincrates.me', 'user', 'user', 1);

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY) values (1, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY) values (1, 2);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY) values (2, 1);